apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cisco-mcn-aks-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sunaofficials/cisco-mcn-cd
    targetRevision: main
    path: aks-prod   # <-- points to folder with raw manifests

  destination:
    server: https://aks-cisco--rg-cisco-mcn-53af53-wfgir91r.hcp.centralindia.azmk8s.io:443
    namespace: cisco-shopping

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
