apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
  namespace: cisco-shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      serviceAccountName: redis-sa

      nodeSelector:
        node-role: db

      securityContext:
        fsGroup: 1000

      containers:
      - name: redis
        image: redis:alpine

        command:
        - sh
        - -c
        - |
          redis-server --requirepass "$(cat /etc/secrets/password)"

        ports:
        - containerPort: 6379

        volumeMounts:
        - name: redis-cart-volume
          mountPath: /data

        - name: redis-secret
          mountPath: /etc/secrets
          readOnly: true

      volumes:
      - name: redis-secret
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: redis-secret-provider

      - name: redis-cart-volume
        persistentVolumeClaim:
          claimName: redis-cart-pvc
