apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  namespace: cisco-shopping
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: checkoutservice
spec:
  type: ClusterIP
  selector:
    app: checkoutservice
  ports:
  - name: grpc
    port: 5050
    targetPort: 5050
